theme: jekyll-theme-cayman
title: Evgeniia Golovina, PhD
description: Curriculum Vitae
show_downloads: false
linkedin: "https://www.linkedin.com/in/evgeniiagolovina/?locale=en_US"
github: "https://github.com/Eugeniia"
twitter: "https://twitter.com/FoffaJn"
researchgate: "https://www.researchgate.net/profile/Evgeniia_Golovina2"
google_scholar: "https://scholar.google.ru/citations?user=cR7t9_8AAAAJ&hl=en&authuser=1"
publons: "https://publons.com/researcher/4650922/evgeniia-golovina/"
